version: '3.8'

services:
  frontend:
      build: 
        context: ./app
      container_name: uber_eats_frontend
      volumes:
        - ./app/:/app/
      ports:
        - 5001:5001
      tty: true
      networks:
        - uber_eats

  frontend_nginx:
      build:
        context: ./web
      container_name: uber_eats_frontend_nginx
      ports:
        - "10051:10051"
      environment:
        TZ: 'Asia/Tokyo'
      volumes:
        - ./web/conf/default.conf:/etc/nginx/conf.d/default.conf
      networks:
        - uber_eats
      depends_on:
        - frontend
  
      
networks:
  uber_eats:
    name: uber_eats
    driver: bridge