version: '3.8'

services:
  backend:
      build: 
        context: ./app
      container_name: uber_eats_backend
      volumes:
        - /app/node_modules
        - ./app:/app/
      environment:
        TZ: 'Asia/Tokyo'
      ports:
        - "4001:10041"
      expose:
        - "4001"
      tty: true
      networks:
        - uber_eats
      depends_on:
        - db
      restart: always
        
  backend_nginx:
      build:
        context: ./web
      container_name: uber_eats_backend_nginx
      ports:
        - "10041:10041"
      environment:
        TZ: 'Asia/Tokyo'
      volumes:
        - ./web/conf/default.conf:/etc/nginx/conf.d/default.conf
      networks:
        - uber_eats
      depends_on:
        - backend
      restart: always

  db:
      build:
        context: ./db
      container_name: uber_eats_db
      ports:
        - 5432:5432
      networks:
        - uber_eats
      volumes:
        - ./db/lib:/var/lib/postgresql/data
        - ./db/init:/docker-entrypoint-initdb.d
      environment:
        POSTGRES_USER: uber_eats
        POSTGRES_PASSWORD: uber_eats
        POSTGRES_DB: uber_eats
        PGDATA: /var/lib/postgresql/data/pgdata
      restart: always
  
      
networks:
  uber_eats:
    name: uber_eats
    driver: bridge